name: Run Maven build
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run tests
        run: |
          cd tutorial4
          mvn clean test
